version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api-ponto-funcionario
    ports:
      - "8095:8095"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/db_apiPontoFuncionario
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0505
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db_apiPontoFuncionario
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0505
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
